# Generated by Django 3.1.14 on 2022-04-14 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='starts_given',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
